### ISSUE TITLE
New data url

### ISSUE THREAD

**Issue by AceChenX** [rschiang/ntu-weather#2]
http://140.112.67.180/data.php or https://www.cwb.gov.tw/V8/C/W/OBS_Station.html?ID=A0A01

**Comment by rschiang** [comment]
Hi CA,

Thanks for reporting! I actually noticed your private plurk message weeks earlier, but I was busy with grad application at the moment. Terribly sorry about that. 💦 

I could do a quick regex patch and push it on production tomorrow. The script currently stores past weather information indefinitely, which might be unplausible for the long term. Do you think it's worth keeping all these minute-wise weather information? Should we either purge the data periodically, or migrate the service to somewhere without quota?

**Comment by rschiang** [comment]
Fixed. Please wait for 24 hours and see if the data populates correctly!
